name: GitHub Actions Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Event
        run: echo "Event name: ${{ github.event_name }}"
      - name: Branch
        run: echo "Branch name: ${{ github.ref_name }}"
      - name: List
        run: ls -la

  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Show env
        run: echo "Deploying to environment: ${{ inputs.environment }}"
