name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment   # lets you pick from Environments (Production, Test, Load-Test)
        required: true
        # default: Production

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Output event name
        run: echo "Event name: ${{ github.event_name }}"
      - name: Output branch name
        run: echo "Branch name: ${{ github.ref_name }}"
      - name: List files in repository
        run: ls -la

  Deploy:
    if: ${{ github.event_name == 'workflow_dispatch' }}  # only when Run workflow is used
    runs-on: ubuntu-latest
    needs: Build
    environment: ${{ inputs.environment }}               # triggers env gates/approvals
    steps:
      - name: Show selected environment
        run: echo "Deploying to environment: ${{ inputs.environment }}"
