name: Minimal Env Picker
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Env
        type: environment
        required: true
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "Env=${{ inputs.environment }}"
